### ISSUE TITLE
False positive "idb-storage"

### ISSUE THREAD

**Issue by eight04** [sindresorhus/npm-name#35] opened 2019-04-02 15:12 UTC
https://repl.it/@eight041/npm-name-test

`idb-storage` is reported as available but you get a 403 error when publishing the package:
```
npm ERR! code E403
npm ERR! 403 Forbidden - PUT https://registry.npmjs.org/idb-storage - Package na
me too similar to existing packages; try renaming your package to '@eight04/idb-
storage' and publishing with 'npm publish --access=public' instead
```

**Comment by sindresorhus** [comment] 2019-05-01 16:07
Duplicate of #15

**Closed by sindresorhus** 2019-05-01 16:07 UTC
